title: "Abschlussarbeitsthemen Professur Climate Change Hydrology (Kristian FÃ¶rster)"
description: "Aktuelle Themenangebote"
remote_theme: pages-themes/minimal@v0.2.0   # GitHub-Standardtheme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: pretty